// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Entrenamiento struct {
	IDEntrenamiento int32          `json:"id_entrenamiento"`
	UsuarioID       int32          `json:"usuario_id"`
	Fecha           time.Time      `json:"fecha"`
	Tipo            string         `json:"tipo"`
	Distancia       string         `json:"distancia"`
	Tiempo          int32          `json:"tiempo"`
	RitmoPromedio   sql.NullString `json:"ritmo_promedio"`
	Calorias        sql.NullInt32  `json:"calorias"`
	Notas           sql.NullString `json:"notas"`
}

type Usuario struct {
	IDUsuario  int32  `json:"id_usuario"`
	Nombre     string `json:"nombre"`
	Email      string `json:"email"`
	Contraseña string `json:"contraseña"`
}
